"use client";
import Image from "next/image";
import { useState } from "react";
import { FlashcardsMode } from "@/app/components/modes/flashcards-mode";
import { LearnMode } from "@/app/components/modes/learn-mode";
import { NotesMode } from "@/app/components/modes/notes-mode";
import { OverviewMode } from "@/app/components/modes/overview-mode";
import { QuizMode } from "@/app/components/modes/quiz-mode";
import type { Flashcard, FlashcardRating, Note, QuizAttempt, StoredWorkspace, WorkspaceActionResult, WorkspaceMode } from "@/lib/workspace/schema";

const labels: Record<WorkspaceMode, string> = { overview: "Übersicht", notes: "Notizen", flashcards: "Karteikarten", quiz: "Quiz", learn: "Lernen" };
type Props = { stored: StoredWorkspace; recent: StoredWorkspace[]; focusMode: boolean; onUpdate: (item: StoredWorkspace) => void; onOpen: (id: string) => void; onDelete: (id: string) => void; onNew: () => void };
export function StudyWorkspace({ stored, recent, focusMode, onUpdate, onOpen, onDelete, onNew }: Props) {
  const { workspace, progress } = stored; const [name, setName] = useState(workspace.title);
  const quizCount = Object.values(workspace.quizzes).reduce((sum, list) => sum + list.length, 0);
  const available: WorkspaceMode[] = ["overview", ...(workspace.bulletPoints.length || workspace.summary || workspace.explanation ? ["notes" as const] : []), ...(workspace.flashcards.length ? ["flashcards" as const] : []), ...(quizCount ? ["quiz" as const] : []), ...(workspace.quizzes.multipleChoice.length ? ["learn" as const] : [])];
  const activeTab = available.includes(progress.lastMode) ? progress.lastMode : "overview";
  const patch = (next: Partial<StoredWorkspace>) => onUpdate({ workspace: next.workspace ?? workspace, progress: next.progress ?? progress });
  const setMode = (mode: WorkspaceMode) => patch({ progress: { ...progress, lastMode: mode } });
  function rename() { const title = name.trim(); if (title && title !== workspace.title) patch({ workspace: { ...workspace, title, updatedAt: new Date().toISOString() } }); else setName(workspace.title); }
  function mastery(conceptId: string | null, delta: number) { if (!conceptId) return; patch({ progress: { ...progress, conceptMastery: { ...progress.conceptMastery, [conceptId]: Math.max(0, Math.min(100, (progress.conceptMastery[conceptId] ?? 35) + delta)) } } }); }
  function rate(card: Flashcard, rating: FlashcardRating) { const delta = rating === "easy" ? 10 : rating === "good" ? 6 : rating === "hard" ? -2 : -7; patch({ progress: { ...progress, flashcardRatings: { ...progress.flashcardRatings, [card.id]: rating }, conceptMastery: card.conceptId ? { ...progress.conceptMastery, [card.conceptId]: Math.max(0, Math.min(100, (progress.conceptMastery[card.conceptId] ?? 35) + delta)) } : progress.conceptMastery } }); }
  function action(note: Note, result: WorkspaceActionResult) { if (result.explanation) patch({ progress: { ...progress, noteEnhancements: { ...progress.noteEnhancements, [note.id]: { simplerExplanation: result.explanation } } } }); if (result.flashcard) patch({ workspace: { ...workspace, flashcards: [...workspace.flashcards, { ...result.flashcard, id: crypto.randomUUID() }], updatedAt: new Date().toISOString() } }); if (result.question) patch({ workspace: { ...workspace, quizzes: { ...workspace.quizzes, multipleChoice: [...workspace.quizzes.multipleChoice, { ...result.question, id: crypto.randomUUID() }] }, updatedAt: new Date().toISOString() } }); }
  return <div className="workspace-shell">{!focusMode ? <aside className="workspace-rail"><div className="rail-logo"><Image src="/assets/lemonlogo.svg" alt="Lemon AI" width={34} height={34} /></div><div className="rail-heading"><span>Aktiver Workspace</span><strong>{workspace.title}</strong></div><nav>{available.map((tab, i) => <button key={tab} className={activeTab === tab ? "active" : ""} onClick={() => setMode(tab)}><span>{labels[tab]}</span><kbd>{i + 1}</kbd></button>)}</nav><div className="recent-list"><span>Zuletzt verwendet</span>{recent.slice(0, 5).map((item) => <div key={item.workspace.id}><button className={item.workspace.id === workspace.id ? "active" : ""} onClick={() => onOpen(item.workspace.id)}>{item.workspace.title}</button><button aria-label={`${item.workspace.title} löschen`} onClick={() => onDelete(item.workspace.id)}>×</button></div>)}</div><button className="rail-new" onClick={onNew}>＋ Neuer Workspace</button></aside> : null}<main className="workspace-main"><header className="workspace-titlebar"><div><p className="eyebrow">{workspace.sourceLanguage} · {workspace.request.difficulty}</p><input value={name} onChange={(e) => setName(e.target.value)} onBlur={rename} onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()} aria-label="Workspace umbenennen" /></div><div className="workspace-stats"><span><b>{workspace.flashcards.length}</b> Karten</span><span><b>{quizCount}</b> Fragen</span></div></header>{!focusMode ? <nav className="mobile-tabs">{available.map((tab) => <button key={tab} className={activeTab === tab ? "active" : ""} onClick={() => setMode(tab)}>{labels[tab]}</button>)}</nav> : null}<div className="workspace-content">{activeTab === "overview" ? <OverviewMode workspace={workspace} progress={progress} onNavigate={setMode} /> : null}{activeTab === "notes" ? <NotesMode workspace={workspace} explanations={progress.noteEnhancements} onApplyAction={action} /> : null}{activeTab === "flashcards" ? <FlashcardsMode flashcards={workspace.flashcards} ratings={progress.flashcardRatings} onRate={rate} /> : null}{activeTab === "quiz" ? <QuizMode quizzes={workspace.quizzes} onAnswer={mastery} onComplete={(attempt: QuizAttempt) => patch({ progress: { ...progress, quizAttempts: [...progress.quizAttempts, attempt] } })} /> : null}{activeTab === "learn" ? <LearnMode workspace={workspace} mastery={progress.conceptMastery} onMasteryChange={mastery} /> : null}</div></main></div>;
}
