"use client";
import { useMemo, useState } from "react";
import type { QuizAttempt, StudyWorkspace } from "@/lib/workspace/schema";
type Kind = keyof StudyWorkspace["quizzes"];
type Item = { id: string; prompt: string; answers: string[]; correct: string; accepted: string[]; explanation: string; conceptId: string | null };
const titles: Record<Kind, string> = { multipleChoice: "Multiple Choice", trueFalse: "Wahr / Falsch", shortAnswer: "Kurzantwort", fillBlank: "Lückentext" };
const normalize = (value: string) => value.toLocaleLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu, " ");
export function QuizMode({ quizzes, onAnswer, onComplete }: { quizzes: StudyWorkspace["quizzes"]; onAnswer: (id: string | null, delta: number) => void; onComplete: (attempt: QuizAttempt) => void }) {
  const available = (Object.keys(quizzes) as Kind[]).filter((kind) => quizzes[kind].length);
  const [kind, setKind] = useState<Kind>(available[0]); const [index, setIndex] = useState(0); const [value, setValue] = useState(""); const [answered, setAnswered] = useState(false); const [correct, setCorrect] = useState(false); const [score, setScore] = useState(0); const [mistakes, setMistakes] = useState<string[]>([]); const [complete, setComplete] = useState(false); const [reviewIds, setReviewIds] = useState<string[] | null>(null);
  const items = useMemo<Item[]>(() => {
    if (kind === "multipleChoice") return quizzes.multipleChoice.map((q) => ({ id:q.id,prompt:q.question,answers:q.options,correct:q.correctAnswer,accepted:[q.correctAnswer],explanation:q.explanation,conceptId:q.conceptId }));
    if (kind === "trueFalse") return quizzes.trueFalse.map((q) => ({ id:q.id,prompt:q.statement,answers:["Richtig","Falsch"],correct:q.correctAnswer ? "Richtig" : "Falsch",accepted:[q.correctAnswer ? "Richtig" : "Falsch"],explanation:q.explanation,conceptId:q.conceptId }));
    if (kind === "shortAnswer") return quizzes.shortAnswer.map((q) => ({ id:q.id,prompt:q.question,answers:[],correct:q.expectedAnswer,accepted:q.acceptedAnswers,explanation:q.explanation,conceptId:q.conceptId }));
    return quizzes.fillBlank.map((q) => ({ id:q.id,prompt:q.sentence,answers:[],correct:q.answer,accepted:q.acceptedAnswers,explanation:q.explanation,conceptId:q.conceptId }));
  }, [kind, quizzes]);
  const session = reviewIds ? items.filter((item) => reviewIds.includes(item.id)) : items; const question = session[index];
  function choose(next: Kind) { setKind(next); reset(); }
  function submit() { if (!value.trim() || answered) return; const answer = normalize(value); const ok = question.accepted.some((candidate) => { const expected = normalize(candidate); return answer === expected || (answer.length > 8 && answer.includes(expected)); }); setCorrect(ok); setAnswered(true); if (ok) setScore((x) => x + 1); else setMistakes((x) => [...x, question.id]); onAnswer(question.conceptId, ok ? 7 : -6); }
  function next() { if (index + 1 < session.length) { setIndex((x) => x + 1); setValue(""); setAnswered(false); } else { setComplete(true); onComplete({ id: crypto.randomUUID(), type: kind, score, total: session.length, incorrectIds: mistakes, completedAt: new Date().toISOString() }); } }
  function reset(ids: string[] | null = null) { setIndex(0); setValue(""); setAnswered(false); setScore(0); setMistakes([]); setComplete(false); setReviewIds(ids); }
  if (complete) return <div className="quiz-complete"><p className="eyebrow">Durchlauf beendet</p><strong>{Math.round((score / session.length) * 100)}<span>%</span></strong><h2>{score} von {session.length} richtig</h2><div className="adaptive-actions">{mistakes.length ? <button className="outline-button" onClick={() => reset(mistakes)}>Fehler wiederholen</button> : null}<button className="primary-button" onClick={() => reset()}>Quiz neu starten</button></div></div>;
  return <div className="quiz-layout"><header className="quiz-header"><div><p className="eyebrow">Aktive Abfrage</p><h2>Prüfe dein Verständnis.</h2></div><div className="score-chip"><span>{score}</span> Punkte</div></header><div className="quiz-type-tabs">{available.map((type) => <button key={type} className={kind === type ? "active" : ""} onClick={() => choose(type)}>{titles[type]}</button>)}</div><div className="quiz-progress"><span>Aufgabe {index + 1} von {session.length}</span><i><b style={{width:`${((index+1)/session.length)*100}%`}} /></i><span>{titles[kind]}</span></div><section className="question-panel"><h3>{question.prompt}</h3>{question.answers.length ? <div className="answer-grid">{question.answers.map((answer,i) => <button key={answer} className={answered ? answer === question.correct ? "correct" : value === answer ? "incorrect" : "" : value === answer ? "selected" : ""} onClick={() => !answered && setValue(answer)}><span>{String.fromCharCode(65+i)}</span>{answer}</button>)}</div> : <textarea className="quiz-text-answer" rows={4} value={value} disabled={answered} onChange={(e) => setValue(e.target.value)} placeholder="Deine Antwort …" />}{!answered ? <button className="primary-button quiz-submit" disabled={!value.trim()} onClick={submit}>Antwort prüfen</button> : <div className={`answer-feedback ${correct ? "correct" : "incorrect"}`}><div><strong>{correct ? "Richtig" : "Noch nicht ganz"}</strong>{!correct ? <span>Antwort: {question.correct}</span> : null}<p>{question.explanation}</p></div><button onClick={next}>{index + 1 === session.length ? "Ergebnis" : "Weiter"} →</button></div>}</section></div>;
}
